name: Deploy to Pagesmith (DigitalOcean)

on:
  push:
    branches:
      - main

jobs:
  deploy_pagesmith:
    name: Deploy Pagesmith to DigitalOcean
    runs-on: ubuntu-latest

    steps:
      - name: SSH into DigitalOcean and deploy
        run: |
          # Save the private key from secrets and secure it
          echo "${{ secrets.SSH_PRIVATE_KEY_DO }}" > ssh_key
          chmod 600 ssh_key

          # SSH and deploy
          ssh -o StrictHostKeyChecking=no -i ssh_key root@159.65.159.179 << 'EOF'
          
            # Install pnpm globally if missing
            if ! command -v pnpm >/dev/null; then
              npm install -g pnpm
            fi

            # Install pm2 globally if missing
            if ! command -v pm2 >/dev/null; then
              npm install -g pm2
            fi

            cd Pagesmith && git pull origin main
            pnpm install
            pnpm run build
            pm2 restart http || pm2 start dist/http.js --name http
            pm2 restart wb || pm2 start dist/wb.js --name wb
          EOF
